from playwright.sync_api import sync_playwright
import google.generativeai as genai
import os
from dotenv import load_dotenv
import logging

# Load API Key and Validate
load_dotenv()
gemini_api_key = os.getenv("GEMINI_API_KEY")
if not gemini_api_key:
    raise ValueError("❌ GEMINI_API_KEY not found. Please check your .env file.")

genai.configure(api_key=gemini_api_key)
logging.getLogger('google').setLevel(logging.ERROR)

def get_css_selectors(url):
    """Use Gemini API to generate accurate CSS selectors."""
    prompt = (
        f"Generate exactly 5 CSS selectors for scraping reviews from this page: {url}. "
        "Return only CSS selectors separated by newlines. No backticks, no numbering, no labels."
    )
    try:
        model = genai.GenerativeModel("gemini-pro")
        response = model.generate_content(prompt)
        selectors = [line.strip() for line in response.text.splitlines() if line.strip()]

        # Clean up the selectors to remove any unexpected labels or numbering
        selectors = [selector.lstrip('0123456789.').strip() for selector in selectors]

        if len(selectors) != 5:
            raise ValueError("Incorrect number of CSS Selectors generated.")
        
        return selectors
    except Exception as e:
        return {"error": f"Failed to fetch CSS selectors: {str(e)}"}


def scrape_reviews(url):
    """Scrape reviews using Playwright and Gemini-generated selectors."""
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)  # Debug mode enabled
        page = browser.new_page()

        try:
            # Set User-Agent to avoid bot detection
            page.set_extra_http_headers({"User-Agent": "Mozilla/5.0"})
            page.goto(url, timeout=90000, wait_until="load")

            # Scroll for lazy loading
            for _ in range(5):
                page.evaluate("window.scrollTo(0, document.body.scrollHeight);")
                page.wait_for_timeout(3000)

        except Exception as e:
            browser.close()
            return {"error": f"Failed to load page: {str(e)}"}

        # Generate CSS Selectors using Gemini
        css_selectors = get_css_selectors(url)
        print("\n✅ CSS Selectors:", css_selectors)

        # Validate Selectors
        if not css_selectors or len(css_selectors) != 5:
            browser.close()
            return {"error": "Invalid CSS selectors generated by Gemini."}

        # Attempt to detect review section
        try:
            # Debugging: Print page content before checking the selector
            print("✅ Printing page content for manual inspection...")
            print(page.content())  # To verify if reviews exist at all
            page.wait_for_selector(css_selectors[0], timeout=30000)
        except Exception as e:
            browser.close()
            return {"error": f"Review section not found: {str(e)}"}

        # Extract Reviews Using the Selectors
        try:
            reviews = page.evaluate(f'''
            Array.from(document.querySelectorAll('{css_selectors[0]}')).map(review => ({{
                title: review.querySelector('{css_selectors[1]}')?.innerText.trim() || "No title",
                body: review.querySelector('{css_selectors[2]}')?.innerText.trim() || "No body",
                rating: review.querySelector('{css_selectors[3]}')?.innerText.trim() || "No rating",
                reviewer: review.querySelector('{css_selectors[4]}')?.innerText.trim() || "Anonymous"
            }}))
            ''')
        except Exception as e:
            browser.close()
            return {"error": f"Error extracting reviews: {str(e)}"}

        browser.close()
        return reviews